### ISSUE TITLE
How to generate  the Gantt Chart with GIFs format?

### ISSUE THREAD

**Issue by DS-cmd** [prosysscience/RL-Job-Shop-Scheduling#23]
Dear prosysscience:
   I'm currently using this code for our work. I want to know how to generate  the Gantt Chart with GIFs format like the gantt chart in your README.md.
   Thank you in advance for answering the questions!

**Comment by ingambe** [comment]
Hello,
We are happy to hear you find our work useful :)
You can have a look at the code we used to generate the GIF in the README: https://github.com/prosysscience/JSSEnv/blob/2a5bbe07726f3c1088017074f634f31e62aa03b3/tests/test_rendering.py
