### ISSUE TITLE
Python-Version?

### ISSUE THREAD

**Issue by ClemeSto** [prosysscience/RL-Job-Shop-Scheduling#24]
First of all, I want to compliment you on this project and the paper! Thanks a lot for making it public!
However, I could not find the Python version you used for the project. I would like to know it for setting the project up as smoothly as possible.

**Comment by ingambe** [comment]
Thank you for your encouraging words :)
We used Python 3.8
To be more precise, our testing environment is based on google's TensorFlow 2.2 GPU docker container: [gcr.io/deeplearning-platform-release/tf2-gpu.2-2](https://gcr.io/deeplearning-platform-release/tf2-gpu.2-2)
It helped us to avoid the burden of setting up everything from scratch

**Comment by ClemeSto** [comment]
Cool, thanks a lot! That’s very helpful! :-)
