### ISSUE TITLE
How to modify main.py to output solution schedule?

### ISSUE THREAD

**Issue by kenghweeng** [prosysscience/RL-Job-Shop-Scheduling#25]
Hi authors,

Thank you for writing such an innovative paper, I really enjoyed the detailed elaborations :)

I just wanted to know how to modify the `main.py` such that I'm able to output the solution schedule, and eventually render the Gantt chart based on that solution. I understand that the `gym.Wrapper` class, in particular, `BestActionsWrapper` is there in the `env_wrapper.py`, but how do I integrate that into `main.py`. Pardon my newbie question, and thank you in advance!

**Comment by ingambe** [comment]
Hi Keng,

Thanks a lot for the compliments :)

There may be multiple ways to do it. The simplest approach IMO would be to use the callback to store the best solution found.

In CustomCallbacks:
```

class CustomCallbacks(DefaultCallbacks):
    
    def __init__(self, legacy_callbacks_dict: Dict[str, callable] = None):
        super(CustomCallbacks, self).__init__(legacy_callbacks_dict)
        self.best_solution_makespan = float('inf')
        self.best_solution = None

    def on_episode_end(self, worker: "RolloutWorker", base_env: BaseEnv,
                       policies: Dict[PolicyID, Policy],
                       episode: MultiAgentEpisode, **kwargs):
        env = base_env.get_unwrapped()[0]
        if env.last_time_step != float('inf'):
            episode.custom_metrics['make_span'] = env.last_time_step
            if env.last_time_step < self.best_solution_makespan:
                self.best_solution_makespan = env.last_time_step
                self.best_solution = env.solution


```
In main, get the best solution back:
```

print(f'best solution makespan {config['callbacks'].best_solution_makespan}')
print(f'best solution {config['callbacks'].best_solution}')

```
Tell me if it solves the issue :)

**Comment by kenghweeng** [comment]
Assuming I've made the correct modifications in the `CustomCallbacks` class, I've modified the `while` loop of the original `main` to be:
```
trainer = PPOTrainer(config=config)
while start_time + stop['time_total_s'] > time.time():
        result = trainer.train()

        result = wandb_tune._clean_log(result)
        log, config_update = _handle_result(result)
        wandb.log(log)
        # wandb.config.update(config_update, allow_val_change=True)

ray.shutdown()
print(f'best solution makespan {config['callbacks'].best_solution_makespan}')
print(f'best solution {config['callbacks'].best_solution}')
```

It will throw: `AttributeError: type object 'CustomCallbacks' has no attribute 'best_solution_makespan'`

**Comment by kenghweeng** [comment]
Something else I also tried was:
```
trainer = PPOTrainer(config=config)
while start_time + stop['time_total_s'] > time.time():
        result = trainer.train()
        result = wandb_tune._clean_log(result)
        log, config_update = _handle_result(result)
        wandb.log(log)
        # wandb.config.update(config_update, allow_val_change=True)

ray.shutdown()
# Basically instantiate the Callback object
curr_callback = config["callbacks"]
print(f'best solution makespan {curr_callback().best_solution_makespan}')
print(f'best solution {curr_callback().best_solution}')
```

But, I just got this:
```
best solution makespan inf
best solution None
```

**Comment by ingambe** [comment]
I've doubled check and effectively, even when I put the variables as static for the `CustomCallbacks`, it seems to be overwritten

It was a bit tricky but I finally managed to store the solution, I had to modify the environment to store the best solution as the `on_episode_end` method of RLLib is not really called at the end of the episode and because of that the solution was not saved properly

The code is available in its own branch: https://github.com/prosysscience/RL-Job-Shop-Scheduling/tree/save_solution
Please give it a try and tell me if it works :)

**Comment by kenghweeng** [comment]
I'd try and let you know soon! One more quick question, I understand that for me to generate the Gantt chart, I would need both the solution, as well as the instance matrix right?

Or can I generate the Gantt chart directly from the solution generated?

**Comment by kenghweeng** [comment]
Okay, I'll let you know! I'd probably write a helper to generate the Gantt chart based on the solution generated, and create a PR :)
