### ISSUE TITLE
About instance specifications

### ISSUE THREAD

**Issue by pop134** [prosysscience/RL-Job-Shop-Scheduling#26]
Hi authors,

Thanks for the great work of the paper and code.
I have a question about the format of input instances. As you mentioned in README.md, the instances must follow Taillard's specification at ```http://jobshop.jjvh.nl/explanation.php#taillard_def```.
But when I checked out given instances at ```JSS/instances/*``` , they are following standard specification instead.
Did the website changed the specification format or am I not understanding the instructions.

**Comment by kenghweeng** [comment]
It is indeed the standard specification, it should be straightforward to change it to the Taillard's specification though.

**Comment by pop134** [comment]
Yeah, I just want to clear it out for the code modifications.
