### ISSUE TITLE
Specification of the solution

### ISSUE THREAD

**Issue by D-Doge** [prosysscience/RL-Job-Shop-Scheduling#34]
Hello,

thank you first of all for the paper and the code. I do however have a small question about the specification of the solution.
When I run main.py from the [save_soltion-branch](https://github.com/prosysscience/RL-Job-Shop-Scheduling/tree/save_solution), I get a 2D-array called best_solution (main.py line 167 prints this array). But I don't really understand what numbers in this array mean.
When I run main.py with an instance, that has 2 Jobs with 15 machines, the solution looks like this:
[[  0  94 160 193 246 272 287 352 434 444 471 564 656 752 822]
 [  0  74 105 193 244 301 434 442 449 540 619 637 688 706 805]]
 
At first, I thought it follows the specification of the [Solution start file](http://jobshop.jjvh.nl/explanation.php#solutions_start), but as far I understand that would mean, that both jobs start machine 1 at time 0. And also, both jobs would start at machine 4 at time 193. But a machine can only work at one job at any given time.

So I wanted to ask, how exactly should we interpret the solution? 
Since I might be missing something really obvious here, I want to thank you again for your time and for the effort you put in to make your research accessible.

Kind regards,
D-Doge

**Comment by D-Doge** [comment]
I am basicaly asking, how to interperted the output of this line:
https://github.com/prosysscience/RL-Job-Shop-Scheduling/blob/7450883175d605679523d74ce171e6f6527d5d66/JSS/main.py#L167

Since it always seems to output a 2D-Array that contains numbers that are way lager then, the number of machines or jobs.
Unlike the code here, in JSSEnv, where the rendering is tested.
https://github.com/prosysscience/JSSEnv/blob/a3c528c158f78e2f6eb5720b499348a3f00579be/tests/test_rendering.py#L19

**Comment by ingambe** [comment]
Hi,

Thank you for the issue and your interest in our work.
Yes, at first, due to technical reasons, we only extract the makespan but not the solution.

However, if you want to extract also the solution, I would not do it using the link you mentioned.
But rather by modifying the `CustomCallbacks.py` files:

```python
from typing import Dict
from ray.rllib.agents.callbacks import DefaultCallbacks
from ray.rllib.env import BaseEnv
from ray.rllib.evaluation import MultiAgentEpisode, RolloutWorker
from ray.rllib.policy import Policy
from ray.rllib.utils.typing import PolicyID
import numpy as np


class CustomCallbacks(DefaultCallbacks):
    
    def __init__(self, legacy_callbacks_dict: Dict[str, callable] = None):
        super(CustomCallbacks, self).__init__(legacy_callbacks_dict)
        
        
    def on_episode_start(
        self,
        *,
        worker: "RolloutWorker",
        base_env: BaseEnv,
        policies: Dict[str, Policy],
        episode: MultiAgentEpisode,
        env_index: int,
        **kwargs
    ):
        episode.user_data["mk_solution"] = float('inf')
        

    def on_episode_end(self, worker: "RolloutWorker", base_env: BaseEnv,
                       policies: Dict[PolicyID, Policy],
                       episode: MultiAgentEpisode, **kwargs):
        env = base_env.get_unwrapped()[0]
        if env.last_time_step != float('inf'):
            episode.custom_metrics['make_span'] = env.last_time_step
            if env.last_time_step < episode.user_data["mk_solution"]:
                episode.user_data["mk_solution"] = env.last_time_step
                with open('solution.npy', 'wb') as f:
                    np.save(f, env.last_solution)

```

This will solve the solution inside a `solution.npy` file.

You can then load and print using a script like this one:

```python
import numpy as np

with open('solution.npy', 'rb') as f:
    a = np.load(f)
    print(a)
```

I hope it helps :)

**Comment by D-Doge** [comment]
Thank you very much for the response.
This works for me, so I am going to close this issue :)

**Comment by avijit15** [comment]
Hello,

I am trying to run this code to get the solution array. I am running the main.py file from save_solution_brunch and I have also updated the CustomsCallbacks.py file as mentioned above. 
After running the main.py I am not getting that  solution.npy file as mentioned above, while I am getting some other output  as log.
> 2022-12-12 14:41:18,357 INFO services.py:1173 -- View the Ray dashboard at http://127.0.0.1:8265

Since I might be missing something here, could you please help me to rectify where I am doing the mistake. Thank you for your time and effort.

Regards,
Avijit Pyne

**Comment by mf093087** [comment]
![image](https://user-images.githubusercontent.com/67538561/211913988-bc241f48-5dc3-445d-be13-0aa265e45a57.png)

**Comment by ingambe** [comment]
Can you try to upgrade the environment package?

```bash
pip install --upgrade JSSEnv
```

**Comment by mf093087** [comment]
I updated the environment and run this code

```
import numpy as np
from numpy import shape

with open('solution.npy', 'rb') as f:
    a = np.load(f)
    print(a)
arr = (list(np.load("solution.npy")))

b = arr
print("----------------")
print(shape(arr))
```


This is what I got from the terminal:
```
[[   0   94  164  191  244  270  442  507  662  701  735  881 1018 1114
  1294]
 [   0  219  293  381  471  535  643  651  676  803  941 1034 1085 1103
  1202]
 [   0   28  126  439  537  589  773  794  800  854  929 1011 1031 1085
  1120]
 [   0   73   96  283  389  442  715  804  897  932 1023 1076 1132 1202
  1357]
 [   0  110  211  326  417  453  504  728  850  929 1005 1098 1140 1219
  1261]
 [  73  102  210  300  370  386  432  497  599  710  753  854  970 1032
  1046]
 [   0   18   93  133  137  313  422  441  495  590  683  729  753  794
   904]
 [   0  167  219  244  298  370  497  596  677  683  897  954 1067 1070
  1127]
 [   0   85  115  228  322  335  422  507  590  668  745  830  838  973
  1136]
 [  94  115  174  204  264  305  405  471  560  638  736  805  850  991
  1005]
 [  74  164  191  192  250  359  448  613  669  701  777  909 1002 1032
  1067]
 [   0   49   92  202  232  386  389  473  507  535  596  665  710  777
   904]
 [ 102  167  229  326  346  381  414  536  665  724  861  909  999 1074
  1188]
 [   0   28  174  225  341  587  676  805  929 1011 1053 1070 1120 1140
  1184]
 [  85  142  160  414  453  490  528  596  669  674  726  867  954 1070
  1114]]
----------------
(15, 15)

Process finished with exit code 0
```


However, when I check here https://github.com/prosysscience/JSSEnv/blob/2a5bbe07726f3c1088017074f634f31e62aa03b3/tests/test_rendering.py, 
the solution should be something like this

solution_sequence = [
            [7, 11, 9, 10, 8, 3, 12, 2, 14, 5, 1, 6, 4, 0, 13],
            [2, 8, 7, 14, 6, 13, 9, 11, 4, 5, 12, 3, 10, 1, 0],
            [11, 9, 3, 0, 4, 12, 8, 7, 5, 2, 6, 14, 13, 10, 1],
            [6, 5, 0, 9, 12, 7, 11, 10, 14, 1, 13, 2, 3, 4, 8],
            [10, 13, 0, 4, 1, 5, 14, 3, 7, 6, 12, 8, 2, 9, 11],
            [5, 7, 3, 12, 13, 10, 1, 11, 8, 4, 2, 6, 0, 9, 14],
            [9, 0, 4, 8, 3, 11, 13, 14, 6, 12, 10, 2, 1, 7, 5],
            [4, 6, 7, 10, 0, 11, 1, 9, 3, 5, 13, 14, 8, 2, 12],
            [13, 4, 6, 2, 9, 14, 12, 11, 7, 10, 0, 1, 3, 8, 5],
            [9, 3, 2, 4, 13, 11, 12, 1, 0, 7, 8, 5, 14, 10, 6],
            [8, 14, 4, 3, 11, 12, 9, 0, 10, 13, 5, 1, 6, 2, 7],
            [7, 9, 8, 5, 6, 0, 2, 3, 1, 13, 14, 12, 4, 10, 11],
            [6, 0, 7, 11, 5, 14, 10, 2, 4, 13, 8, 9, 3, 12, 1],
            [13, 10, 7, 9, 5, 3, 11, 1, 12, 14, 2, 4, 0, 6, 8],
            [13, 11, 6, 8, 7, 4, 1, 5, 3, 10, 0, 14, 9, 2, 12]
        ]

**Comment by mf093087** [comment]
Any update?

**Comment by ingambe** [comment]
The format of the solution sequence in the rendering unit test differs from that provided by the agent. 
In the unit test, the solution must be presented in the order of jobs to be executed for each machine. 
On the other hand, the solution generated by the environment lists the start time for each operation for each job.

**Comment by Abh4git** [comment]
Thank you for the explanation. If I understand right 'environment lists the start time for each operation for each job.'
Does it mean to say starttime of job 
For 6 jobs and 6 machines
[[  0  40  70  80 100 140]
 [  0  20  30  50  60  90]
 [  0  30  40  60 100 120]
 [ 10  60  80 100 120 140]
 [  0  20  40  50  70  80]
 [  0  40  60  70  90 100]]

Let us look at first array which is for say job 1
[  0  40  70  80 100 140]
0 is starttime for job1 on machine1. 40 is starttime of job1 on machine2, 70 is starttime of job1 on machine 3 and so on. Am I right?
