### ISSUE TITLE
Is the code working?

### ISSUE THREAD

**Issue by mf093087** [prosysscience/RL-Job-Shop-Scheduling#36]
I am not so familiar with Ray, when I run the main.py, I got this output, is this correct? Should I wait?
![image](https://user-images.githubusercontent.com/67538561/211223732-14252cbb-a658-45d9-b7c9-11f23af9462e.png)

**Comment by ingambe** [comment]
Those are warnings, not errors.
Check the output on weights and biases

**Comment by mf093087** [comment]
> Those are warnings, not errors. Check the output on weights and biases

Thanks a lot! Where can I find the output on weights and biases?

**Comment by mf093087** [comment]
I have found this in wandb! However, I only found the make span, do you know where I could find the solution?

This https://github.com/prosysscience/RL-Job-Shop-Scheduling/issues/34 doesn't work...

**Comment by mf093087** [comment]
can anybody help me? I really appreciate it...

**Comment by ingambe** [comment]
Let's continue this discussion on #34 to not have duplicated
